[workspace]
resolver = "2"
members = [
    "gvrtex",
    "gvrtex_macros"
]

[workspace.package]
version = "0.1.0"
authors = ["Sten-Kristjan Prantsu <xortile@gmail.com>"]
license = "MIT"
edition = "2021"
